### ISSUE TITLE
"&" in uri seems have problem

### ISSUE THREAD

**Issue by edouardlicn123** [schmurtzm/Gamelist-Translator#1]
所在位置 C:\Users\marab\Desktop\Gamelist-Translator-main\Gamelist-Translator.ps1:65 字符: 75
+ ... tps://translate.googleapis.com/translate_a/single?client=gtx&sl=auto& ...
+                                                                 ~
不允许使用与号(&)。& 运算符是为将来使用而保留的；请用双引号将与号引起来("&")，以将其作为字符串的一部分传递。
所在位置 C:\Users\marab\Desktop\Gamelist-Translator-main\Gamelist-Translator.ps1:65 字符: 83
+ ... anslate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=$($Ta ...
+                                                                 ~
不允许使用与号(&)。& 运算符是为将来使用而保留的；请用双引号将与号引起来("&")，以将其作为字符串的一部分传递。
所在位置 C:\Users\marab\Desktop\Gamelist-Translator-main\Gamelist-Translator.ps1:65 字符: 105
+ ... /translate_a/single?client=gtx&sl=auto&tl=$($TargetLanguage)&dt=t&q=$ ...
+                                                                 ~
不允许使用与号(&)。& 运算符是为将来使用而保留的；请用双引号将与号引起来("&")，以将其作为字符串的一部分传递。
所在位置 C:\Users\marab\Desktop\Gamelist-Translator-main\Gamelist-Translator.ps1:65 字符: 110
+ ... slate_a/single?client=gtx&sl=auto&tl=$($TargetLanguage)&dt=t&q=$Text  ...
+                                                                 ~
不允许使用与号(&)。& 运算符是为将来使用而保留的；请用双引号将与号引起来("&")，以将其作为字符串的一部分传递。
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

**Comment by edouardlicn123** [comment]
It looks like the ”“ should be ""

**Comment by schmurtzm** [comment]
Merge done, is it OK like that ?

**Comment by edouardlicn123** [comment]
> 

Yes, fine.

**Comment by schmurtzm** [comment]
👍
